### ISSUE TITLE
App token?

### ISSUE THREAD

**Issue by dagumak** [moneytree/mt-link-javascript-sdk#2]
1) This has a space after the period: https://github.com/moneytree/mt-link-javascript-sdk/blob/master/src/index.ts#L35
2) https://github.com/moneytree/mt-link-javascript-sdk/blob/master/src/index.ts#L39 `config.appToken` looks wrong to me here? I would expect the access token to always come from the server on authentication and is set on runtime rather than through a configuration. I would also suggest `appToken` to be called accessToken to maintain a ubiquitous language.

**Comment by mt-micky** [comment]
1. Feel free to send a PR
2. Your app might already have the access token in the time of the init. If not, you can use the `setToken` method

**Comment by mt-micky** [comment]
PS: we will remove the concept of passing the token. The vault will have its own token.
