### ISSUE TITLE
Settings doesn't have the possibility of updating the continue parameter

### ISSUE THREAD

**Issue by mt-neus** [moneytree/mt-link-javascript-sdk#20]
In order to know from where the application called myaccount, it would be necessary that the openSettings call can accept the continue parameter.

Currently it only accepts the backTo, which enables us to return to our application from myaccount. But once we are in our application there is no way to know from where we came from.

Suggestion: add a continueTo update parameter in the openSettings function.

**Comment by mt-micky** [comment]
Not sure it makes sense. the `continueTo` params will at best be appended to the `backTo` url.
In that case, I would suggest you to add to the url, all the params you need instead.

Let me know if something doesn't behave correctly.

**Comment by mt-neus** [comment]
It won't work because I initialize my app with the continue. The two entry points are different.
One gives me the backTo, then it goes again to my account and I need to have the continueTo updated to be able to redirect.

Currently the vault is not using the sdk for opening the settings because of the same issue.

**Comment by mt-micky** [comment]
I still don't understand your issue. If you use `backTo` and set URL with params you need then you won't need `continueTo`.
`continueTo` is used due to the restriction of the `redirect_uri` during authentication for your app.

**Comment by mt-neus** [comment]
Solved with the backTo. no need for further changes.
